/**
 * Generated by `npm run db:types` from supabase/migrations. Do not edit by hand.
 * A unit test fails if this file is out of date with the migrations.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      concept_mastery: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          concept_id: string;
          status: string;
          attempts: number;
          correct_count: number;
          last_two_correct: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_id: string;
          concept_id: string;
          status?: string;
          attempts?: number;
          correct_count?: number;
          last_two_correct?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string;
          concept_id?: string;
          status?: string;
          attempts?: number;
          correct_count?: number;
          last_two_correct?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concept_mastery_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: false;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
          {
            foreignKeyName: "concept_mastery_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      concept_sign_links: {
        Row: {
          id: string;
          lesson_id: string;
          concept_id: string;
          sign_clip_id: string;
          verified: boolean;
          verified_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          concept_id: string;
          sign_clip_id: string;
          verified?: boolean;
          verified_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          concept_id?: string;
          sign_clip_id?: string;
          verified?: boolean;
          verified_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concept_sign_links_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: true;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
          {
            foreignKeyName: "concept_sign_links_sign_clip_id_fkey";
            columns: ["sign_clip_id"];
            isOneToOne: false;
            referencedRelation: "sign_clips";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "concept_sign_links_verified_by_fkey";
            columns: ["verified_by"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      concept_variants: {
        Row: {
          id: string;
          lesson_id: string;
          concept_id: string;
          graph_version: number;
          reading_level: string;
          body: string;
          summary: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          concept_id: string;
          graph_version: number;
          reading_level: string;
          body: string;
          summary: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          concept_id?: string;
          graph_version?: number;
          reading_level?: string;
          body?: string;
          summary?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concept_variants_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: false;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
        ];
      };
      concepts: {
        Row: {
          id: string;
          lesson_id: string;
          graph_version: number;
          order_index: number;
          title: string;
          summary: string;
          key_term: string | null;
          retired: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          lesson_id: string;
          graph_version: number;
          order_index: number;
          title: string;
          summary: string;
          key_term?: string | null;
          retired?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          graph_version?: number;
          order_index?: number;
          title?: string;
          summary?: string;
          key_term?: string | null;
          retired?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concepts_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_jobs: {
        Row: {
          id: string;
          lesson_id: string;
          stage: string;
          progress: number;
          error: string | null;
          artifacts: Json;
          tokens_in: number;
          tokens_out: number;
          cost_usd: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          stage?: string;
          progress?: number;
          error?: string | null;
          artifacts?: Json;
          tokens_in?: number;
          tokens_out?: number;
          cost_usd?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          stage?: string;
          progress?: number;
          error?: string | null;
          artifacts?: Json;
          tokens_in?: number;
          tokens_out?: number;
          cost_usd?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_jobs_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      learning_events: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          graph_version: number;
          type: string;
          concept_id: string | null;
          quiz_item_id: string | null;
          correct: boolean | null;
          duration_ms: number | null;
          layout: string;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          lesson_id: string;
          graph_version: number;
          type: string;
          concept_id?: string | null;
          quiz_item_id?: string | null;
          correct?: boolean | null;
          duration_ms?: number | null;
          layout: string;
          occurred_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string;
          graph_version?: number;
          type?: string;
          concept_id?: string | null;
          quiz_item_id?: string | null;
          correct?: boolean | null;
          duration_ms?: number | null;
          layout?: string;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "learning_events_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "learning_events_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      lessons: {
        Row: {
          id: string;
          owner_id: string;
          org_id: string | null;
          title: string;
          status: string;
          source_type: string | null;
          source_path: string | null;
          graph: Json | null;
          graph_version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          org_id?: string | null;
          title?: string;
          status?: string;
          source_type?: string | null;
          source_path?: string | null;
          graph?: Json | null;
          graph_version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          org_id?: string | null;
          title?: string;
          status?: string;
          source_type?: string | null;
          source_path?: string | null;
          graph?: Json | null;
          graph_version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lessons_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      quiz_items: {
        Row: {
          id: string;
          lesson_id: string;
          concept_id: string;
          type: string;
          retired: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          lesson_id: string;
          concept_id: string;
          type: string;
          retired?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          concept_id?: string;
          type?: string;
          retired?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quiz_items_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: false;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
          {
            foreignKeyName: "quiz_items_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      render_profiles: {
        Row: {
          user_id: string;
          profile: Json;
          share_with_teachers: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          profile: Json;
          share_with_teachers?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          profile?: Json;
          share_with_teachers?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "render_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      sign_clips: {
        Row: {
          id: string;
          gloss: string;
          language: string;
          storage_path: string;
          source: string;
          license: string;
          signer_credit: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          gloss: string;
          language?: string;
          storage_path: string;
          source: string;
          license: string;
          signer_credit?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          gloss?: string;
          language?: string;
          storage_path?: string;
          source?: string;
          license?: string;
          signer_credit?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      unmet_needs: {
        Row: { id: string; user_id: string | null; request_text: string; created_at: string };
        Insert: { id?: string; user_id?: string | null; request_text: string; created_at?: string };
        Update: {
          id?: string;
          user_id?: string | null;
          request_text?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "unmet_needs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      users_public: {
        Row: { id: string; display_name: string; is_creator: boolean; created_at: string };
        Insert: { id: string; display_name?: string; is_creator?: boolean; created_at?: string };
        Update: { id?: string; display_name?: string; is_creator?: boolean; created_at?: string };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_entitled: { Args: { p_user: string; p_lesson: string }; Returns: boolean };
      owns_lesson: { Args: { p_lesson: string }; Returns: boolean };
      publish_lesson: { Args: { p_lesson_id: string; p_graph: Json }; Returns: number };
      try_uuid: { Args: { p_text: string }; Returns: string };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
