/**
 * Generated by `npm run db:types` from supabase/migrations. Do not edit by hand.
 * A unit test fails if this file is out of date with the migrations.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      assignments: {
        Row: {
          id: string;
          classroom_id: string;
          lesson_id: string;
          due_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          classroom_id: string;
          lesson_id: string;
          due_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          classroom_id?: string;
          lesson_id?: string;
          due_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "assignments_classroom_id_fkey";
            columns: ["classroom_id"];
            isOneToOne: false;
            referencedRelation: "classrooms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "assignments_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_log: {
        Row: {
          id: string;
          org_id: string | null;
          actor_id: string | null;
          action: string;
          target: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id?: string | null;
          actor_id?: string | null;
          action: string;
          target?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string | null;
          actor_id?: string | null;
          action?: string;
          target?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_log_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      classrooms: {
        Row: {
          id: string;
          org_id: string;
          teacher_id: string;
          name: string;
          grade: string | null;
          subject: string | null;
          join_code: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          teacher_id: string;
          name: string;
          grade?: string | null;
          subject?: string | null;
          join_code: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          teacher_id?: string;
          name?: string;
          grade?: string | null;
          subject?: string | null;
          join_code?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "classrooms_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "classrooms_teacher_id_fkey";
            columns: ["teacher_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      concept_mastery: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          concept_id: string;
          status: string;
          attempts: number;
          correct_count: number;
          last_two_correct: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          lesson_id: string;
          concept_id: string;
          status?: string;
          attempts?: number;
          correct_count?: number;
          last_two_correct?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string;
          concept_id?: string;
          status?: string;
          attempts?: number;
          correct_count?: number;
          last_two_correct?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concept_mastery_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: false;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
          {
            foreignKeyName: "concept_mastery_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      concept_sign_links: {
        Row: {
          id: string;
          lesson_id: string;
          concept_id: string;
          sign_clip_id: string;
          verified: boolean;
          verified_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          concept_id: string;
          sign_clip_id: string;
          verified?: boolean;
          verified_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          concept_id?: string;
          sign_clip_id?: string;
          verified?: boolean;
          verified_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concept_sign_links_lesson_fk";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "concept_sign_links_sign_clip_id_fkey";
            columns: ["sign_clip_id"];
            isOneToOne: false;
            referencedRelation: "sign_clips";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "concept_sign_links_verified_by_fkey";
            columns: ["verified_by"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      concept_variants: {
        Row: {
          id: string;
          lesson_id: string;
          concept_id: string;
          graph_version: number;
          reading_level: string;
          body: string;
          summary: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          concept_id: string;
          graph_version: number;
          reading_level: string;
          body: string;
          summary: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          concept_id?: string;
          graph_version?: number;
          reading_level?: string;
          body?: string;
          summary?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concept_variants_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: false;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
        ];
      };
      concepts: {
        Row: {
          id: string;
          lesson_id: string;
          graph_version: number;
          order_index: number;
          title: string;
          summary: string;
          key_term: string | null;
          retired: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          lesson_id: string;
          graph_version: number;
          order_index: number;
          title: string;
          summary: string;
          key_term?: string | null;
          retired?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          graph_version?: number;
          order_index?: number;
          title?: string;
          summary?: string;
          key_term?: string | null;
          retired?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "concepts_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      course_lessons: {
        Row: { course_id: string; lesson_id: string; order_index: number; is_preview: boolean };
        Insert: { course_id: string; lesson_id: string; order_index: number; is_preview?: boolean };
        Update: {
          course_id?: string;
          lesson_id?: string;
          order_index?: number;
          is_preview?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "course_lessons_course_id_fkey";
            columns: ["course_id"];
            isOneToOne: false;
            referencedRelation: "courses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "course_lessons_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      courses: {
        Row: {
          id: string;
          creator_id: string;
          title: string;
          slug: string;
          description: string;
          cover_path: string | null;
          cover_alt: string | null;
          price_cents: number;
          currency: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          title: string;
          slug: string;
          description?: string;
          cover_path?: string | null;
          cover_alt?: string | null;
          price_cents?: number;
          currency?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          creator_id?: string;
          title?: string;
          slug?: string;
          description?: string;
          cover_path?: string | null;
          cover_alt?: string | null;
          price_cents?: number;
          currency?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "courses_creator_id_fkey";
            columns: ["creator_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      creator_accounts: {
        Row: {
          user_id: string;
          stripe_account_id: string | null;
          onboarding_complete: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          stripe_account_id?: string | null;
          onboarding_complete?: boolean;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          stripe_account_id?: string | null;
          onboarding_complete?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "creator_accounts_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      enrollments: {
        Row: { classroom_id: string; student_id: string; created_at: string };
        Insert: { classroom_id: string; student_id: string; created_at?: string };
        Update: { classroom_id?: string; student_id?: string; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "enrollments_classroom_id_fkey";
            columns: ["classroom_id"];
            isOneToOne: false;
            referencedRelation: "classrooms";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "enrollments_student_id_fkey";
            columns: ["student_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_jobs: {
        Row: {
          id: string;
          lesson_id: string;
          stage: string;
          progress: number;
          error: string | null;
          artifacts: Json;
          tokens_in: number;
          tokens_out: number;
          cost_usd: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lesson_id: string;
          stage?: string;
          progress?: number;
          error?: string | null;
          artifacts?: Json;
          tokens_in?: number;
          tokens_out?: number;
          cost_usd?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          stage?: string;
          progress?: number;
          error?: string | null;
          artifacts?: Json;
          tokens_in?: number;
          tokens_out?: number;
          cost_usd?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_jobs_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      learning_events: {
        Row: {
          id: string;
          user_id: string;
          lesson_id: string;
          graph_version: number;
          type: string;
          concept_id: string | null;
          quiz_item_id: string | null;
          correct: boolean | null;
          duration_ms: number | null;
          layout: string;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          lesson_id: string;
          graph_version: number;
          type: string;
          concept_id?: string | null;
          quiz_item_id?: string | null;
          correct?: boolean | null;
          duration_ms?: number | null;
          layout: string;
          occurred_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          lesson_id?: string;
          graph_version?: number;
          type?: string;
          concept_id?: string | null;
          quiz_item_id?: string | null;
          correct?: boolean | null;
          duration_ms?: number | null;
          layout?: string;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "learning_events_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "learning_events_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      lessons: {
        Row: {
          id: string;
          owner_id: string;
          org_id: string | null;
          title: string;
          status: string;
          source_type: string | null;
          source_path: string | null;
          graph: Json | null;
          graph_version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          org_id?: string | null;
          title?: string;
          status?: string;
          source_type?: string | null;
          source_path?: string | null;
          graph?: Json | null;
          graph_version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          org_id?: string | null;
          title?: string;
          status?: string;
          source_type?: string | null;
          source_path?: string | null;
          graph?: Json | null;
          graph_version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "lessons_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      org_memberships: {
        Row: { org_id: string; user_id: string; role: string; created_at: string };
        Insert: { org_id: string; user_id: string; role: string; created_at?: string };
        Update: { org_id?: string; user_id?: string; role?: string; created_at?: string };
        Relationships: [
          {
            foreignKeyName: "org_memberships_org_id_fkey";
            columns: ["org_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "org_memberships_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          monthly_spend_cap_usd: number | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          monthly_spend_cap_usd?: number | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          monthly_spend_cap_usd?: number | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organizations_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      purchases: {
        Row: {
          id: string;
          buyer_id: string;
          course_id: string;
          stripe_session_id: string | null;
          amount_cents: number;
          platform_fee_cents: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          buyer_id: string;
          course_id: string;
          stripe_session_id?: string | null;
          amount_cents: number;
          platform_fee_cents?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          buyer_id?: string;
          course_id?: string;
          stripe_session_id?: string | null;
          amount_cents?: number;
          platform_fee_cents?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "purchases_buyer_id_fkey";
            columns: ["buyer_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "purchases_course_id_fkey";
            columns: ["course_id"];
            isOneToOne: false;
            referencedRelation: "courses";
            referencedColumns: ["id"];
          },
        ];
      };
      quiz_items: {
        Row: {
          id: string;
          lesson_id: string;
          concept_id: string;
          type: string;
          retired: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          lesson_id: string;
          concept_id: string;
          type: string;
          retired?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          lesson_id?: string;
          concept_id?: string;
          type?: string;
          retired?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quiz_items_lesson_id_concept_id_fkey";
            columns: ["lesson_id", "concept_id"];
            isOneToOne: false;
            referencedRelation: "concepts";
            referencedColumns: ["lesson_id", "id"];
          },
          {
            foreignKeyName: "quiz_items_lesson_id_fkey";
            columns: ["lesson_id"];
            isOneToOne: false;
            referencedRelation: "lessons";
            referencedColumns: ["id"];
          },
        ];
      };
      render_profiles: {
        Row: {
          user_id: string;
          profile: Json;
          share_with_teachers: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          profile: Json;
          share_with_teachers?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          profile?: Json;
          share_with_teachers?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "render_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      sign_clips: {
        Row: {
          id: string;
          gloss: string;
          language: string;
          storage_path: string;
          source: string;
          license: string;
          signer_credit: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          gloss: string;
          language?: string;
          storage_path: string;
          source: string;
          license: string;
          signer_credit?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          gloss?: string;
          language?: string;
          storage_path?: string;
          source?: string;
          license?: string;
          signer_credit?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      unmet_needs: {
        Row: { id: string; user_id: string | null; request_text: string; created_at: string };
        Insert: { id?: string; user_id?: string | null; request_text: string; created_at?: string };
        Update: {
          id?: string;
          user_id?: string | null;
          request_text?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "unmet_needs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users_public";
            referencedColumns: ["id"];
          },
        ];
      };
      users_public: {
        Row: { id: string; display_name: string; is_creator: boolean; created_at: string };
        Insert: { id: string; display_name?: string; is_creator?: boolean; created_at?: string };
        Update: { id?: string; display_name?: string; is_creator?: boolean; created_at?: string };
        Relationships: [];
      };
    };
    Views: {
      v_classroom_concept_difficulty: {
        Row: {
          classroom_id: string | null;
          lesson_id: string | null;
          concept_id: string | null;
          concept_title: string | null;
          attempts: number | null;
          correct: number | null;
          error_rate: number | null;
        };
        Relationships: [];
      };
      v_classroom_student_progress: {
        Row: {
          classroom_id: string | null;
          student_id: string | null;
          display_name: string | null;
          lesson_id: string | null;
          total_concepts: number | null;
          mastered_concepts: number | null;
          answered: number | null;
          correct: number | null;
          active_seconds: number | null;
        };
        Relationships: [];
      };
      v_org_classroom_summary: {
        Row: {
          org_id: string | null;
          classroom_id: string | null;
          classroom_name: string | null;
          teacher_id: string | null;
          students: number | null;
          assigned_lessons: number | null;
          active_learners: number | null;
          completion: number | null;
          average_mastery: number | null;
        };
        Relationships: [];
      };
      v_org_layout_usage: {
        Row: {
          org_id: string | null;
          layout: string | null;
          learners: number | null;
          share: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_classroom_principal: { Args: { p_classroom: string }; Returns: boolean };
      is_classroom_teacher: { Args: { p_classroom: string }; Returns: boolean };
      is_enrolled: { Args: { p_classroom: string }; Returns: boolean };
      is_entitled: { Args: { p_user: string; p_lesson: string }; Returns: boolean };
      org_role: { Args: { p_org: string }; Returns: string };
      owns_course: { Args: { p_course: string }; Returns: boolean };
      owns_lesson: { Args: { p_lesson: string }; Returns: boolean };
      publish_lesson: { Args: { p_lesson_id: string; p_graph: Json }; Returns: number };
      try_uuid: { Args: { p_text: string }; Returns: string };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
