import { format, resolveConfig } from "prettier";
import type { Db } from "../src/tests/sql/harness";

/**
 * Generates `src/lib/supabase/database.types.ts` from a migrated PGlite database.
 *
 * `supabase gen types` needs a running local stack (Docker) or a hosted project. This
 * generator reads the same migrations in-process and emits the same `Database` shape,
 * so typed queries work without either. `npm run db:types:supabase` runs the official
 * generator when a stack is available; the output shapes are intentionally compatible.
 */

interface ColumnRow {
  table_name: string;
  column_name: string;
  udt_name: string;
  is_nullable: "YES" | "NO";
  column_default: string | null;
  is_generated: "ALWAYS" | "NEVER";
  table_type: "BASE TABLE" | "VIEW";
}

interface ForeignKeyRow {
  constraint_name: string;
  table_name: string;
  columns: string[];
  referenced_table: string;
  referenced_columns: string[];
  is_one_to_one: boolean;
}

interface FunctionRow {
  name: string;
  arg_names: string[] | null;
  arg_types: string[];
  arg_defaults: number;
  return_type: string;
  returns_set: boolean;
}

export const HEADER = `/**
 * Generated by \`npm run db:types\` from supabase/migrations. Do not edit by hand.
 * A unit test fails if this file is out of date with the migrations.
 */
`;

const NUMBER_TYPES = new Set([
  "int2",
  "int4",
  "int8",
  "float4",
  "float8",
  "numeric",
  "oid",
  "serial",
]);
const BOOLEAN_TYPES = new Set(["bool"]);
const JSON_TYPES = new Set(["json", "jsonb"]);

/** Maps a Postgres type name (udt_name) to its TypeScript type. */
export function tsType(udt: string): string {
  if (udt.startsWith("_")) {
    const inner = tsType(udt.slice(1));
    return inner.includes(" ") ? `(${inner})[]` : `${inner}[]`;
  }
  if (NUMBER_TYPES.has(udt)) return "number";
  if (BOOLEAN_TYPES.has(udt)) return "boolean";
  if (JSON_TYPES.has(udt)) return "Json";
  if (udt === "void") return "undefined";
  return "string"; // text, uuid, timestamptz, date, varchar, and anything else
}

function quote(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) ? name : JSON.stringify(name);
}

export async function generateDatabaseTypes(db: Db): Promise<string> {
  const columns = (
    await db.query<ColumnRow>(`
      select c.table_name, c.column_name, c.udt_name, c.is_nullable, c.column_default,
             c.is_generated, t.table_type
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
      where c.table_schema = 'public'
      order by c.table_name, c.ordinal_position
    `)
  ).rows;

  const foreignKeys = (
    await db.query<ForeignKeyRow>(`
      select con.conname as constraint_name,
             src.relname as table_name,
             array(select a.attname from unnest(con.conkey) with ordinality k(attnum, ord)
                   join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.attnum
                   order by k.ord) as columns,
             ref.relname as referenced_table,
             array(select a.attname from unnest(con.confkey) with ordinality k(attnum, ord)
                   join pg_attribute a on a.attrelid = con.confrelid and a.attnum = k.attnum
                   order by k.ord) as referenced_columns,
             exists (
               select 1 from pg_constraint u
               where u.conrelid = con.conrelid and u.contype in ('p', 'u') and u.conkey = con.conkey
             ) as is_one_to_one
      from pg_constraint con
      join pg_class src on src.oid = con.conrelid
      join pg_namespace sn on sn.oid = src.relnamespace
      join pg_class ref on ref.oid = con.confrelid
      join pg_namespace rn on rn.oid = ref.relnamespace
      where con.contype = 'f' and sn.nspname = 'public' and rn.nspname = 'public'
      order by src.relname, con.conname
    `)
  ).rows;

  const functions = (
    await db.query<FunctionRow>(`
      select p.proname as name,
             p.proargnames as arg_names,
             array(select t.typname from unnest(p.proargtypes::oid[]) with ordinality u(oid, ord)
                   join pg_type t on t.oid = u.oid order by u.ord) as arg_types,
             p.pronargdefaults as arg_defaults,
             rt.typname as return_type,
             p.proretset as returns_set
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      join pg_type rt on rt.oid = p.prorettype
      where n.nspname = 'public'
        and p.prokind = 'f'
        and rt.typname <> 'trigger'
      order by p.proname
    `)
  ).rows;

  const tables = new Map<string, ColumnRow[]>();
  const views = new Map<string, ColumnRow[]>();
  for (const column of columns) {
    const target = column.table_type === "VIEW" ? views : tables;
    target.set(column.table_name, [...(target.get(column.table_name) ?? []), column]);
  }

  const columnType = (column: ColumnRow) =>
    `${tsType(column.udt_name)}${column.is_nullable === "YES" ? " | null" : ""}`;

  const relationships = (table: string) => {
    const keys = foreignKeys.filter((key) => key.table_name === table);
    if (keys.length === 0) return "Relationships: []";
    const items = keys.map(
      (key) => `{
        foreignKeyName: ${JSON.stringify(key.constraint_name)}
        columns: ${JSON.stringify(key.columns)}
        isOneToOne: ${key.is_one_to_one}
        referencedRelation: ${JSON.stringify(key.referenced_table)}
        referencedColumns: ${JSON.stringify(key.referenced_columns)}
      }`,
    );
    return `Relationships: [${items.join(", ")}]`;
  };

  const tableBlocks = [...tables.entries()].map(([name, cols]) => {
    const row = cols.map((c) => `${quote(c.column_name)}: ${columnType(c)}`).join("\n");
    const insert = cols
      .map((c) => {
        const optional =
          c.is_nullable === "YES" || c.column_default !== null || c.is_generated === "ALWAYS";
        return `${quote(c.column_name)}${optional ? "?" : ""}: ${columnType(c)}`;
      })
      .join("\n");
    const update = cols.map((c) => `${quote(c.column_name)}?: ${columnType(c)}`).join("\n");
    return `${quote(name)}: {
      Row: { ${row} }
      Insert: { ${insert} }
      Update: { ${update} }
      ${relationships(name)}
    }`;
  });

  const viewBlocks = [...views.entries()].map(([name, cols]) => {
    const row = cols.map((c) => `${quote(c.column_name)}: ${tsType(c.udt_name)} | null`).join("\n");
    return `${quote(name)}: { Row: { ${row} }, Relationships: [] }`;
  });

  const functionBlocks = functions.map((fn) => {
    const names = fn.arg_names ?? [];
    const args =
      fn.arg_types.length === 0
        ? "Record<PropertyKey, never>"
        : `{ ${fn.arg_types
            .map((type, index) => {
              const optional = index >= fn.arg_types.length - fn.arg_defaults;
              const argName = names[index] || `arg${index + 1}`;
              return `${quote(argName)}${optional ? "?" : ""}: ${tsType(type)}`;
            })
            .join("\n")} }`;
    const returns = tsType(fn.return_type);
    return `${quote(fn.name)}: { Args: ${args}; Returns: ${fn.returns_set ? `${returns}[]` : returns} }`;
  });

  const source = `${HEADER}
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      ${tableBlocks.join("\n")}
    }
    Views: ${viewBlocks.length ? `{ ${viewBlocks.join("\n")} }` : "{ [_ in never]: never }"}
    Functions: ${functionBlocks.length ? `{ ${functionBlocks.join("\n")} }` : "{ [_ in never]: never }"}
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
`;

  const config = (await resolveConfig(`${process.cwd()}/src/lib/supabase/database.types.ts`)) ?? {};
  return format(source, { ...config, parser: "typescript" });
}
