-- Private storage buckets and their policies (PRD task P1-09, section 6.4, brief section 38).
--
-- All three buckets are private. Source documents in particular must never be publicly
-- readable: they are a teacher's or creator's original material, uploaded on the
-- understanding that Prism processes it, not that it republishes it.
--
-- Access is through short-lived signed URLs generated server-side, with expiry capped at one
-- hour by the PRD and defaulted lower here. Object paths are generated by the server from the
-- owner and lesson ids - never from the client's filename - which is what makes the first
-- path segment trustworthy enough to authorise against.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'sources', 'sources', false, 52428800,
    array[
      'application/pdf',
      'text/plain',
      'text/markdown',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/mp4', 'audio/x-m4a'
    ]
  ),
  (
    'lesson-media', 'lesson-media', false, 52428800,
    array['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']
  ),
  (
    'sign-clips', 'sign-clips', false, 52428800,
    array['video/mp4', 'video/webm']
  )
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ---------------------------------------------------------------------------
-- sources: objects live at sources/{owner_id}/{lesson_id}/{random}.{ext}
--
-- The first path segment is the owner id, so ownership is checkable from the path alone
-- without a join. This only holds because the server generates the path; accepting a
-- client-supplied path would make the same check meaningless.
-- ---------------------------------------------------------------------------
create policy sources_owner_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'sources'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy sources_owner_write on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'sources'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy sources_owner_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'sources'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ---------------------------------------------------------------------------
-- lesson-media: objects live at lesson-media/{lesson_id}/{random}.{ext}
--
-- Readable by anyone entitled to the lesson, writable by its owner. Images are part of what a
-- learner sees, so entitlement rather than ownership governs reads.
-- ---------------------------------------------------------------------------
create policy lesson_media_entitled_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'lesson-media'
    and (
      (storage.foldername(name))[1]::uuid
        in (select private.entitled_lesson_ids((select auth.uid())))
    )
  );

create policy lesson_media_owner_write on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'lesson-media'
    and (storage.foldername(name))[1]::uuid in (select private.my_lesson_ids())
  );

create policy lesson_media_owner_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'lesson-media'
    and (storage.foldername(name))[1]::uuid in (select private.my_lesson_ids())
  );

-- ---------------------------------------------------------------------------
-- sign-clips: a shared reference library.
--
-- Readable by any signed-in learner, since a clip is not specific to a lesson. Writes are
-- administrative and happen through the service role, so there is no insert policy here.
-- ---------------------------------------------------------------------------
create policy sign_clips_read on storage.objects
  for select to authenticated
  using (bucket_id = 'sign-clips');
